<a href="https://colab.research.google.com/github/in3der/DataAnalysis/blob/main/%5B%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B6%84%EC%84%9D%EB%B0%8F%ED%99%9C%EC%9A%A9%5DNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# List and Numpy Array  


In [ ]:
import numpy as np

lst = [95., 90., 90., 70, 92, 88, 80]
print(lst)
print(len(lst))
print(type(lst))        # list의 타입. <class 'list'>
print(type(lst[0]))     # 95.의 타입 <class 'float'>
print(type(type(lst[4]))) # 92의 타입 <class 'int'>,     <class 'int'>의 타입 <class 'type'>

arr = np.array(lst)   # list를 np.array로 지정.
print(arr)
print(arr.shape)      # 7열.
print(type(arr))      # np.array의 타입 <class 'numpy.ndarray'>
print(arr.dtype)      # array의 데이터타입은 float64

[95.0, 90.0, 90.0, 70, 92, 88, 80]
7
<class 'list'>
<class 'float'>
<class 'type'>
[95. 90. 90. 70. 92. 88. 80.]
(7,)
<class 'numpy.ndarray'>
float64


# Numpy Array vs. Matrix

In [ ]:
lst = [[95, 90, 90], [70, 92, 88]]
print(np.shape(lst))

arr = np.array(lst, dtype = np.int32)     # np.array 사용, 데이터 타입을 정수로 지정
print(arr)
print(arr.shape)      # 2행 3열
print(type(arr))
print(arr.dtype)

mat = np.matrix(lst, dtype=np.int32)    # np.matrix 사용, 데이터타입을 정수로 지정
print(mat)
print(type(mat))

(2, 3)
[[95 90 90]
 [70 92 88]]
(2, 3)
<class 'numpy.ndarray'>
int32
[[95 90 90]
 [70 92 88]]
<class 'numpy.matrix'>


# Reshape

In [ ]:
# reshape 방법 2가지가 있다
# 방법 1
arr1 = np.arange(16)      # 0 ~ 15까지 리스트를 만든다.
arr2 = np.reshape(arr1, (4, 4))  # 4행 4열의 형식으로 reshape

In [ ]:
# 방법 2
arr1 = np.arange(16)    # 0 ~ 15까지 리스트
arr2 = arr1.reshape(4, 4)   # 4행 4열의 형식으로 reahspe
print(arr1)
print(arr2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
arr1 = np.arange(8)
print(arr1)

arr2 = np.reshape(arr1, (2, -1))    # 2행 고정, 열은 알아서
print(arr2)

arr3 = np.reshape(arr1, (-1, 4))   # 행은 알아서, 4열 고정
print(arr3)

arr4 = np.reshape(arr3, (-1)) # flatter. 1차원으로 만드는 경우
print(arr4)

# 에러생김
# arr5 = np.reshape(arr1, (-1, 3))
# print(arr5)

[0 1 2 3 4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]
[[0 1 2 3]
 [4 5 6 7]]
[0 1 2 3 4 5 6 7]


# Indexing

In [ ]:
arr1 = np.arange(12)
arr2 = arr1.reshape(2, -1)      # 0~11을 2행 n열로 reshape
print(arr1) # [ 0  1  2  3  4  5  6  7  8  9 10 11]
print(arr2)  # [[ 0  1  2  3  4  5]
              #[ 6  7  8  9 10 11]]

print(arr1[0])  # 0
print(arr2[0])  # [0 1 2 3 4 5]

print(arr2[0, 0])  # 0

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
0
[0 1 2 3 4 5]
0


In [ ]:
arr1 = np.arange(12)    #  [ 0  1  2  3  4  5  6  7  8  9 10 11]
arr2 = arr1.reshape(2, -1)
#  [[ 0  1  2  3  4  5]
#   [ 6  7  8  9 10 11]]
arr3 = arr1[2:10]   # [2 3 4 5 6 7 8 9]
arr4 = arr2.copy()   # 그냥 arrr2 복사뜨는..

arr2[0, 0] = 4  # arr1 제일 첫 번째 원소에 4로 바꿔넣기

print(arr1)
print(arr2)
print(arr3)
print(arr4)

[ 4  1  2  3  4  5  6  7  8  9 10 11]
[[ 4  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[2 3 4 5 6 7 8 9]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [ ]:
arr1 = np.arange(16)
arr2 = arr1.reshape(4, -1)    # 4행 n열 - 4행 4열
print(arr2)

print(arr2[1, 3])
print(arr2[0, 1])
print(arr2[2, 2])

print(arr2[[1, 0, 2], [3, 1, 2]])   ##!!!! 위와 똑같이 원소 뽑는 것임. 근데 출력은 리스트로

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
7
1
10
[ 7  1 10]


# Slicing

In [ ]:
arr = np.arange(16).reshape(4, 4)

print(arr)
print(arr[1:3, 1:3])    # 2번째 ~ 3번째 행 & 2번째 ~ 3번째 열
print(arr[:, :])
print(arr[1:, :-1])   # 2번째 행 ~ 끝 & 맨 뒤의 열 뺀다

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 5  6]
 [ 9 10]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 4  5  6]
 [ 8  9 10]
 [12 13 14]]


# Exercise

In [ ]:
import numpy as np
A = np.array([[400, 500, 600], [500, 300, 500], [700, 400, 700]])
B = np.array([[500, 700, 700], [300, 400, 600], [900, 200, 900]])
print(A)
print(B)

[[400 500 600]
 [500 300 500]
 [700 400 700]]
[[500 700 700]
 [300 400 600]
 [900 200 900]]


## Array Indexing

In [ ]:
# A 행렬에서 1행 2열을 출력하라.
print(A[0, 1])
# A 행렬에서 1-2행을 출력하라.
print(A[0:2, :])
# A 행렬에서 마지막 열을 빼고 출력하라.
print(A[:, :-1])

500
[[400 500 600]
 [500 300 500]]
[[400 500]
 [500 300]
 [700 400]]


In [ ]:
# A의 2열과 B의 1열을 더하라
print(A[:, 1] + B[:, 0])

# A, B 행렬에서 두 번째 행을 빼고 C, D 행렬을 만들어라
C = A[(0, 2), :]
D = B[(0, 2), :]
print(C)
print(D)

[1000  600 1300]
[[400 500 600]
 [700 400 700]]
[[500 700 700]
 [900 200 900]]


## Max, Min, Mean

In [ ]:
# max : 배열에서 가장 큰 값을 고름
print(A.max(), B.max())
# np.maximum : 둘 중에서 가장 큰 값을 고름
print(np.maximum(A.max(), B.max()))

print(A.min(), B.min())
print(np.minimum(A.min(), B.min()))

print(A.min(), B.mean())
print((A.mean() + B.mean()) / 2)

700 900
900
300 200
200
300 577.7777777777778
544.4444444444445


## Max, Min, Means along Axis

In [ ]:
print(A.max(axis=0)) # 각 행에서 가장 큰 값들을 골라옴
print(A.max(axis = 1)) # 각 열에서 가장 큰 값들을 골라옴

[700 500 700]
[600 500 700]


## Argmax, Argmin

In [ ]:
print(B - A)
print(np.abs(A-B)) # abs : 절댓값취함

[[ 100  200  100]
 [-200  100  100]
 [ 200 -200  200]]
[[100 200 100]
 [200 100 100]
 [200 200 200]]


In [ ]:
# argmax, argmin : 최소값, 최대값, 혹은 조건에 해당하는 색인(index) 값을 찾기
print(np.argmax(np.abs(A-B)))
print(np.argmin(np.abs(A-B)))

1
0


# Expend Dimension

In [ ]:
import numpy as np
A = np.random.rand(2, 3, 4)
print(A)

print(A.shape)
print(A[:, np.newaxis, :, :].shape)   # newaxis : 새로운 차원을 끼움
print(A[:, np.newaxis, :, np.newaxis, :].shape)
print(A[..., np.newaxis].shape) ## ...으로 기존을 표현하고 뒤에  newaxis를 끼울 수 있다.

[[[0.69402111 0.09270565 0.03076127 0.85758852]
  [0.60901533 0.93697019 0.78239859 0.40538063]
  [0.34288547 0.28559057 0.83200202 0.52975287]]

 [[0.82512735 0.43734502 0.09811109 0.7575477 ]
  [0.87998869 0.89663512 0.09456482 0.23165138]
  [0.21245149 0.78786812 0.7752833  0.69301741]]]
(2, 3, 4)
(2, 1, 3, 4)
(2, 1, 3, 1, 4)
(2, 3, 4, 1)


# Broadcasting

In [ ]:
a = np.array([0.0, 10.0, 20.0, 30.0]) # (4, )
b = np.array([1.0, 2.0, 3.0]) # (3, )
print(a[:, np.newaxis] + b)   # (4, )에 broadcasting => (4, 3)
print(a + b[:, np.newaxis])   # (3, )에 broadcasting => (3, 4)

[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]
[[ 1. 11. 21. 31.]
 [ 2. 12. 22. 32.]
 [ 3. 13. 23. 33.]]


# repeat  

In [ ]:
  X = np.array([1, 2, 3])
  Y = np.array([[1, 2],
                [3, 4]])

  print(np.repeat(X, 3))    # 같은 원소를 바로 3번 반복한다.
  print(np.repeat(Y, 3))  # 걍 냅다 flatten하고 3번씩 반복

  print(np.repeat(Y, 3, axis=0))  # 행 기준 복사. 여기서 각 원소는 각 row. [1, 2] [3, 4]
  print(np.repeat(Y, 3, axis=1))  # 열 기준 복사. 여기서 각 원소는 각 column [1, 3], [2, 4]

[1 1 1 2 2 2 3 3 3]
[1 1 1 2 2 2 3 3 3 4 4 4]
[[1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]
[[1 1 1 2 2 2]
 [3 3 3 4 4 4]]


# repeat vs. tile

In [ ]:
X = np.array([1, 2, 3])
Y = np.array([[1, 2],
              [3, 4]])

print(np.repeat(X, 3))
print(np.tile(X, 3))  # X라는 배열 하나[1 2 3]를 반복

print(np.tile(Y, [1, 1]))
print(np.tile(Y, [2, 1]))   # 행렬을 axis=0 row 방향으로 2번 반복, axis=1 column 방향으로 1번 반복
print(np.tile(Y, [1, 3]))
print(np.tile(Y, [2, 4]))

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]
[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [1 2]
 [3 4]]
[[1 2 1 2 1 2]
 [3 4 3 4 3 4]]
[[1 2 1 2 1 2 1 2]
 [3 4 3 4 3 4 3 4]
 [1 2 1 2 1 2 1 2]
 [3 4 3 4 3 4 3 4]]


# Stack

In [ ]:
a1 = np.random.rand(5, 100)
a2 = np.random.rand(5, 100)
a3 = np.random.rand(5, 100)

# stack : 배열들의 shape이 전부 동일해야 함

a_stack = np.stack([a1, a2, a3])
a_stack_0 = np.stack([a1, a2, a3], axis=0)

a_stack_1 = np.stack([a1, a2, a3], axis=1)  # 배열을 세로방향으로 쌓음

a_stack_2 = np.stack([a1, a2, a3], axis=2)  # 배열을 가로방향으로 쌓음
a_stack_m = np.stack([a1, a2, a3], axis=-1)   # axis=2와 동일한 효과.

print(a_stack.shape)
print(a_stack_0.shape)
print(a_stack_1.shape)
print(a_stack_2.shape)
print(a_stack_m.shape)

(3, 5, 100)
(3, 5, 100)
(5, 3, 100)
(5, 100, 3)
(5, 100, 3)


# concatenate

In [ ]:
v1 = np.random.rand(10, 4, 3)
v2 = np.random.rand(20, 4, 3)
v3 = np.random.rand(30, 4, 3)

h1 = np.random.rand(5, 10, 3)
h2 = np.random.rand(5, 20, 3)
h3 = np.random.rand(5, 30, 3)

# 나머지 차원이 모두 동일하면 결합 가능

vstack0 = np.vstack([v1, v2, v3])
concat0 = np.concatenate([v1, v2, v3], axis=0)    # 수직으로 쌓기

hstack1 = np.hstack([h1, h2, h3])
concat1 = np.concatenate([h1, h2, h3], axis=1)    # 수평으로 결합

print(vstack0.shape)
print(concat0.shape)
print(hstack1.shape)
print(concat1.shape)

(60, 4, 3)
(60, 4, 3)
(5, 60, 3)
(5, 60, 3)
